/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.Gender;
import com.mycompany.myapp.dto.GenderDTO;
import com.mycompany.myapp.dto.GenderDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.GenderRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/genders")
public class GenderResource {

    private final Logger log = LoggerFactory.getLogger(GenderResource.class);

    @Inject
    private GenderRepository genderRepository;
    @Inject
    private GenderDTOService genderDTOService;

    /**
     * Create a new Gender.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GenderDTO> create(@RequestBody GenderDTO genderDTO) throws URISyntaxException {

        log.debug("Create GenderDTO : {}", genderDTO);

        if (genderDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Gender with existing ID").body(null);
        }

        GenderDTO result = genderDTOService.save(genderDTO);

        return ResponseEntity.created(new URI("/api/genders/" + result.id)).body(result);
    }

    /**
    * Find by id Gender.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GenderDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Gender : {}", id);

        return Optional.ofNullable(genderDTOService.findOne(id)).map(genderDTO -> new ResponseEntity<>(genderDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Gender.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GenderDTO> update(@RequestBody GenderDTO genderDTO) throws URISyntaxException {

        log.debug("Update GenderDTO : {}", genderDTO);

        if (!genderDTO.isIdSet()) {
            return create(genderDTO);
        }

        GenderDTO result = genderDTOService.save(genderDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Gender using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<GenderDTO>> findAll(@RequestBody PageRequestByExample<GenderDTO> prbe) throws URISyntaxException {
        PageResponse<GenderDTO> pageResponse = genderDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<GenderDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<GenderDTO> results = genderDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Gender.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Gender : {}", id);

        try {
            genderRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}