/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.Race;
import com.mycompany.myapp.dto.RaceDTO;
import com.mycompany.myapp.dto.RaceDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.RaceRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/races")
public class RaceResource {

    private final Logger log = LoggerFactory.getLogger(RaceResource.class);

    @Inject
    private RaceRepository raceRepository;
    @Inject
    private RaceDTOService raceDTOService;

    /**
     * Create a new Race.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<RaceDTO> create(@RequestBody RaceDTO raceDTO) throws URISyntaxException {

        log.debug("Create RaceDTO : {}", raceDTO);

        if (raceDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Race with existing ID").body(null);
        }

        RaceDTO result = raceDTOService.save(raceDTO);

        return ResponseEntity.created(new URI("/api/races/" + result.id)).body(result);
    }

    /**
    * Find by id Race.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<RaceDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Race : {}", id);

        return Optional.ofNullable(raceDTOService.findOne(id)).map(raceDTO -> new ResponseEntity<>(raceDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Race.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<RaceDTO> update(@RequestBody RaceDTO raceDTO) throws URISyntaxException {

        log.debug("Update RaceDTO : {}", raceDTO);

        if (!raceDTO.isIdSet()) {
            return create(raceDTO);
        }

        RaceDTO result = raceDTOService.save(raceDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Race using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<RaceDTO>> findAll(@RequestBody PageRequestByExample<RaceDTO> prbe) throws URISyntaxException {
        PageResponse<RaceDTO> pageResponse = raceDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<RaceDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<RaceDTO> results = raceDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Race.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Race : {}", id);

        try {
            raceRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}