/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.RaceOption;
import com.mycompany.myapp.dto.RaceOptionDTO;
import com.mycompany.myapp.dto.RaceOptionDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.RaceOptionRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/raceOptions")
public class RaceOptionResource {

    private final Logger log = LoggerFactory.getLogger(RaceOptionResource.class);

    @Inject
    private RaceOptionRepository raceOptionRepository;
    @Inject
    private RaceOptionDTOService raceOptionDTOService;

    /**
     * Create a new RaceOption.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<RaceOptionDTO> create(@RequestBody RaceOptionDTO raceOptionDTO) throws URISyntaxException {

        log.debug("Create RaceOptionDTO : {}", raceOptionDTO);

        if (raceOptionDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create RaceOption with existing ID").body(null);
        }

        RaceOptionDTO result = raceOptionDTOService.save(raceOptionDTO);

        return ResponseEntity.created(new URI("/api/raceOptions/" + result.id)).body(result);
    }

    /**
    * Find by id RaceOption.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<RaceOptionDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id RaceOption : {}", id);

        return Optional.ofNullable(raceOptionDTOService.findOne(id)).map(raceOptionDTO -> new ResponseEntity<>(raceOptionDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update RaceOption.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<RaceOptionDTO> update(@RequestBody RaceOptionDTO raceOptionDTO) throws URISyntaxException {

        log.debug("Update RaceOptionDTO : {}", raceOptionDTO);

        if (!raceOptionDTO.isIdSet()) {
            return create(raceOptionDTO);
        }

        RaceOptionDTO result = raceOptionDTOService.save(raceOptionDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of RaceOption using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<RaceOptionDTO>> findAll(@RequestBody PageRequestByExample<RaceOptionDTO> prbe) throws URISyntaxException {
        PageResponse<RaceOptionDTO> pageResponse = raceOptionDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<RaceOptionDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<RaceOptionDTO> results = raceOptionDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id RaceOption.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id RaceOption : {}", id);

        try {
            raceOptionRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}