/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.Script;
import com.mycompany.myapp.dto.ScriptDTO;
import com.mycompany.myapp.dto.ScriptDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.ScriptRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/scripts")
public class ScriptResource {

    private final Logger log = LoggerFactory.getLogger(ScriptResource.class);

    @Inject
    private ScriptRepository scriptRepository;
    @Inject
    private ScriptDTOService scriptDTOService;

    /**
     * Create a new Script.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ScriptDTO> create(@RequestBody ScriptDTO scriptDTO) throws URISyntaxException {

        log.debug("Create ScriptDTO : {}", scriptDTO);

        if (scriptDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Script with existing ID").body(null);
        }

        ScriptDTO result = scriptDTOService.save(scriptDTO);

        return ResponseEntity.created(new URI("/api/scripts/" + result.id)).body(result);
    }

    /**
    * Find by id Script.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ScriptDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Script : {}", id);

        return Optional.ofNullable(scriptDTOService.findOne(id)).map(scriptDTO -> new ResponseEntity<>(scriptDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Script.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ScriptDTO> update(@RequestBody ScriptDTO scriptDTO) throws URISyntaxException {

        log.debug("Update ScriptDTO : {}", scriptDTO);

        if (!scriptDTO.isIdSet()) {
            return create(scriptDTO);
        }

        ScriptDTO result = scriptDTOService.save(scriptDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Script using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<ScriptDTO>> findAll(@RequestBody PageRequestByExample<ScriptDTO> prbe) throws URISyntaxException {
        PageResponse<ScriptDTO> pageResponse = scriptDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ScriptDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<ScriptDTO> results = scriptDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Script.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Script : {}", id);

        try {
            scriptRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}