/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.Skill;
import com.mycompany.myapp.dto.SkillDTO;
import com.mycompany.myapp.dto.SkillDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.SkillRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/skills")
public class SkillResource {

    private final Logger log = LoggerFactory.getLogger(SkillResource.class);

    @Inject
    private SkillRepository skillRepository;
    @Inject
    private SkillDTOService skillDTOService;

    /**
     * Create a new Skill.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SkillDTO> create(@RequestBody SkillDTO skillDTO) throws URISyntaxException {

        log.debug("Create SkillDTO : {}", skillDTO);

        if (skillDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Skill with existing ID").body(null);
        }

        SkillDTO result = skillDTOService.save(skillDTO);

        return ResponseEntity.created(new URI("/api/skills/" + result.id)).body(result);
    }

    /**
    * Find by id Skill.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SkillDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Skill : {}", id);

        return Optional.ofNullable(skillDTOService.findOne(id)).map(skillDTO -> new ResponseEntity<>(skillDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Skill.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SkillDTO> update(@RequestBody SkillDTO skillDTO) throws URISyntaxException {

        log.debug("Update SkillDTO : {}", skillDTO);

        if (!skillDTO.isIdSet()) {
            return create(skillDTO);
        }

        SkillDTO result = skillDTOService.save(skillDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Skill using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<SkillDTO>> findAll(@RequestBody PageRequestByExample<SkillDTO> prbe) throws URISyntaxException {
        PageResponse<SkillDTO> pageResponse = skillDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<SkillDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<SkillDTO> results = skillDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Skill.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Skill : {}", id);

        try {
            skillRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}