//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {RaceOption} from '../raceOption/raceOption';
import {Characteristic} from '../characteristic/characteristic';

export class Race {
    // Raw attributes
    id : number;
    name : string;
    description : string;
    imgFile : string;
    creationDate : Date;
    creationAuthor : string;
    lastModificationDate : Date;
    lastModificationAuthor : string;
    version : number;
    // x-to-one
    raceOpt : RaceOption;
    charc : Characteristic;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.name = json.name;
            this.description = json.description;
            this.imgFile = json.imgFile;
            if (json.creationDate != null) {
                this.creationDate = new Date(json.creationDate);
            }
            this.creationAuthor = json.creationAuthor;
            if (json.lastModificationDate != null) {
                this.lastModificationDate = new Date(json.lastModificationDate);
            }
            this.lastModificationAuthor = json.lastModificationAuthor;
            this.version = json.version;

            if (json.raceOpt != null) {
                this.raceOpt = new RaceOption(json.raceOpt);
            }

            if (json.charc != null) {
                this.charc = new Characteristic(json.charc);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : Race[] {
        let races : Race[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                races.push(new Race(json));
            }
        }
        return races;
    }
}
