//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {Race} from './race';
import {RaceService} from './race.service';
import {RaceOption} from '../raceOption/raceOption';
import {Characteristic} from '../characteristic/characteristic';

@Component({
    moduleId: module.id,
	templateUrl: 'race-detail.component.html',
	selector: 'race-detail',
})
export class RaceDetailComponent implements OnInit, OnDestroy {
    race : Race;

    private params_subscription: any;

    showCharacterRace : boolean = true;

    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new Race
    set raceOpt(raceOpt : RaceOption) {
        this.race = new Race();
        this.race.raceOpt = raceOpt;
    }

    @Input() // used to pass the parent when creating a new Race
    set charc(charc : Characteristic) {
        this.race = new Race();
        this.race.charc = charc;
    }

    @Output() onSaveClicked = new EventEmitter<Race>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private raceService: RaceService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for race-detail ' + id);

            if (id === 'new') {
                this.race = new Race();
            } else {
                this.raceService.getRace(id)
                    .subscribe(race => {
                            this.race = race;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoRaceOpt() {
        this.router.navigate(['/raceOption', this.race.raceOpt.id]);
    }

    clearRaceOpt() {
        this.race.raceOpt = null;
    }

    gotoCharc() {
        this.router.navigate(['/characteristic', this.race.charc.id]);
    }

    clearCharc() {
        this.race.charc = null;
    }

    onSave() {
        this.raceService.update(this.race).
            subscribe(
                race => {
                    this.race = race;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.race);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
