/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.mycompany.myapp.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import com.mycompany.myapp.domain.Character;
import com.mycompany.myapp.domain.Character_;

public interface CharacterRepository extends JpaRepository<Character, Integer> {

    /**
     * Return the persistent instance of {@link Character} with the given unique property value username,
     * or null if there is no such persistent instance.
     *
     * @param username the unique value
     * @return the corresponding {@link Character} persistent instance or null
     */
    Character getByUsername(String username);

    default List<Character> complete(String query, int maxResults) {
        Character probe = new Character();
        probe.setUsername(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(Character_.username.getName(), match -> match.ignoreCase().startsWith());

        Page<Character> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}