/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.mycompany.myapp.domain;

import java.time.Instant;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(RaceOption.class)
public abstract class RaceOption_ {

    // Raw attributes
    public static volatile SingularAttribute<RaceOption, Integer> id;
    public static volatile SingularAttribute<RaceOption, Integer> strengthmin;
    public static volatile SingularAttribute<RaceOption, Integer> strengthmax;
    public static volatile SingularAttribute<RaceOption, Integer> agilitymin;
    public static volatile SingularAttribute<RaceOption, Integer> agilitymax;
    public static volatile SingularAttribute<RaceOption, Integer> endurancemin;
    public static volatile SingularAttribute<RaceOption, Integer> endurancemax;
    public static volatile SingularAttribute<RaceOption, Integer> intelligencemin;
    public static volatile SingularAttribute<RaceOption, Integer> intelligencemax;
    public static volatile SingularAttribute<RaceOption, Integer> charismamin;
    public static volatile SingularAttribute<RaceOption, Integer> charismamax;
    public static volatile SingularAttribute<RaceOption, Integer> perceptionmin;
    public static volatile SingularAttribute<RaceOption, Integer> perceptionmax;
    public static volatile SingularAttribute<RaceOption, Integer> luckmin;
    public static volatile SingularAttribute<RaceOption, Integer> luckmax;
    public static volatile SingularAttribute<RaceOption, Integer> heightmin;
    public static volatile SingularAttribute<RaceOption, Integer> heightmax;
    public static volatile SingularAttribute<RaceOption, Integer> weightmin;
    public static volatile SingularAttribute<RaceOption, Integer> weightmax;
    public static volatile SingularAttribute<RaceOption, Instant> creationDate;
    public static volatile SingularAttribute<RaceOption, String> creationAuthor;
    public static volatile SingularAttribute<RaceOption, Instant> lastModificationDate;
    public static volatile SingularAttribute<RaceOption, String> lastModificationAuthor;
    public static volatile SingularAttribute<RaceOption, Integer> version;

    // Many to many
    public static volatile ListAttribute<RaceOption, Gender> theGenders;
    public static volatile ListAttribute<RaceOption, Model> theModels;
}