/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.mycompany.myapp.domain;

import java.time.Instant;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Race.class)
public abstract class Race_ {

    // Raw attributes
    public static volatile SingularAttribute<Race, Integer> id;
    public static volatile SingularAttribute<Race, String> name;
    public static volatile SingularAttribute<Race, String> description;
    public static volatile SingularAttribute<Race, String> imgFile;
    public static volatile SingularAttribute<Race, Instant> creationDate;
    public static volatile SingularAttribute<Race, String> creationAuthor;
    public static volatile SingularAttribute<Race, Instant> lastModificationDate;
    public static volatile SingularAttribute<Race, String> lastModificationAuthor;
    public static volatile SingularAttribute<Race, Integer> version;

    // Many to one
    public static volatile SingularAttribute<Race, RaceOption> raceOpt;
    public static volatile SingularAttribute<Race, Characteristic> charc;

    // One to many
    public static volatile ListAttribute<Race, Character> characterRace;
}