//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {Model} from './model';
import {ModelService} from './model.service';
import {CategoryType} from '../categoryType/categoryType';
import {RaceOption} from '../raceOption/raceOption';
import {RaceOptionService} from '../raceOption/raceOption.service';

@Component({
    moduleId: module.id,
	templateUrl: 'model-detail.component.html',
	selector: 'model-detail',
})
export class ModelDetailComponent implements OnInit, OnDestroy {
    model : Model;

    private params_subscription: any;

    sourceTheGenders : RaceOption[] = [];

    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new Model
    set cat(cat : CategoryType) {
        this.model = new Model();
        this.model.cat = cat;
    }

    @Output() onSaveClicked = new EventEmitter<Model>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private modelService: ModelService, private raceOptionService : RaceOptionService) {
        raceOptionService.complete(null).
            subscribe(theGenders => this.sourceTheGenders = theGenders,
                        error =>  this.messageService.error('Constructor error', error));
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for model-detail ' + id);

            if (id === 'new') {
                this.model = new Model();
            } else {
                this.modelService.getModel(id)
                    .subscribe(model => {
                            this.model = model;
                            this.sourceTheGenders = this.sourceTheGenders.filter(item => this.model.theGenders.map((e) => e.id).indexOf(item.id) < 0);
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoCat() {
        this.router.navigate(['/categoryType', this.model.cat.id]);
    }

    clearCat() {
        this.model.cat = null;
    }

    onSave() {
        this.modelService.update(this.model).
            subscribe(
                model => {
                    this.model = model;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.model);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
