//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {CategoryType} from '../categoryType/categoryType';
import {RaceOption} from '../raceOption/raceOption';

export class Model {
    // Raw attributes
    id : number;
    name : string;
    fileName : string;
    color : string;
    creationDate : Date;
    creationAuthor : string;
    lastModificationDate : Date;
    lastModificationAuthor : string;
    version : number;
    // x-to-one
    cat : CategoryType;
    // many-to-many
    theGenders : RaceOption[];


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.name = json.name;
            this.fileName = json.fileName;
            this.color = json.color;
            if (json.creationDate != null) {
                this.creationDate = new Date(json.creationDate);
            }
            this.creationAuthor = json.creationAuthor;
            if (json.lastModificationDate != null) {
                this.lastModificationDate = new Date(json.lastModificationDate);
            }
            this.lastModificationAuthor = json.lastModificationAuthor;
            this.version = json.version;

            if (json.cat != null) {
                this.cat = new CategoryType(json.cat);
            }

            if (json.theGenders != null) {
                this.theGenders = RaceOption.toArray(json.theGenders);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : Model[] {
        let models : Model[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                models.push(new Model(json));
            }
        }
        return models;
    }
}
