//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {Characteristic} from '../characteristic/characteristic';
import {Race} from '../race/race';
import {Skill} from '../skill/skill';

export class Character {
    // Raw attributes
    id : number;
    username : string;
    creationDate : Date;
    creationAuthor : string;
    lastModificationDate : Date;
    lastModificationAuthor : string;
    version : number;
    // x-to-one
    charc : Characteristic;
    race : Race;
    // many-to-many
    theSkills : Skill[];


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.username = json.username;
            if (json.creationDate != null) {
                this.creationDate = new Date(json.creationDate);
            }
            this.creationAuthor = json.creationAuthor;
            if (json.lastModificationDate != null) {
                this.lastModificationDate = new Date(json.lastModificationDate);
            }
            this.lastModificationAuthor = json.lastModificationAuthor;
            this.version = json.version;

            if (json.charc != null) {
                this.charc = new Characteristic(json.charc);
            }

            if (json.race != null) {
                this.race = new Race(json.race);
            }

            if (json.theSkills != null) {
                this.theSkills = Skill.toArray(json.theSkills);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : Character[] {
        let characters : Character[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                characters.push(new Character(json));
            }
        }
        return characters;
    }
}
