//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, OnChanges, EventEmitter, SimpleChanges } from '@angular/core';
import { Router } from '@angular/router';
import { DataTable, LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { MdDialog } from '@angular/material';
import { ConfirmDeleteDialogComponent } from "../../support/confirm-delete-dialog.component";
import { Character } from './character';
import { CharacterDetailComponent } from './character-detail.component';
import { CharacterService } from './character.service';
import { Characteristic } from '../characteristic/characteristic';
import { CharacteristicLineComponent } from '../characteristic/characteristic-line.component';
import { Race } from '../race/race';
import { RaceLineComponent } from '../race/race-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'character-list.component.html',
	selector: 'character-list'
})
export class CharacterListComponent {

    @Input() header = "Characters...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    characterToDelete : Character;

    // basic search criterias (visible if not in 'sub' mode)
    example : Character = new Character();

    // list is paginated
    currentPage : PageResponse<Character> = new PageResponse<Character>(0,0,[]);

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _charc : Characteristic;
    private _race : Race;

    constructor(private router : Router,
        private characterService : CharacterService,
        private messageService : MessageService,
        private confirmDeleteDialog: MdDialog) {
    }

    /**
     * When used as a 'sub' component (to display one-to-many list), refreshes the table
     * content when the input changes.
     */
    ngOnChanges(changes: SimpleChanges) {
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.characterService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set charc(charc : Characteristic) {
        if (charc == null) {
            return;
        }
        this._charc = charc;

        this.example = new Character();
        this.example.charc = new Characteristic();
        this.example.charc.id = this._charc.id;
    }

    @Input()
    set race(race : Race) {
        if (race == null) {
            return;
        }
        this._race = race;

        this.example = new Character();
        this.example.race = new Race();
        this.example.race.id = this._race.id;
    }


    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/character', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/character', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let characterToDelete : Character = <Character> rowData;

        let dialogRef = this.confirmDeleteDialog.open(ConfirmDeleteDialogComponent);
        dialogRef.afterClosed().subscribe(result => {
            if (result === 'delete') {
                this.delete(characterToDelete);
            }
        });
    }

    private delete(characterToDelete : Character) {
        let id =  characterToDelete.id;

        this.characterService.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(characterToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}