/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import java.time.Instant;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for Characteristic.
 */
public class CharacteristicDTO {
    public Integer id;
    public Integer strength;
    public Integer agility;
    public Integer endurance;
    public Integer intelligence;
    public Integer charisma;
    public Integer perception;
    public Integer luck;
    public Integer pointsAvailable;
    public Integer skillAvailable;
    public Instant creationDate;
    public String creationAuthor;
    public Instant lastModificationDate;
    public String lastModificationAuthor;
    public Integer version;
    public CharacterDTO characteristics;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}