/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import java.time.Instant;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for RaceOption.
 */
public class RaceOptionDTO {
    public Integer id;
    public Integer strengthmin;
    public Integer strengthmax;
    public Integer agilitymin;
    public Integer agilitymax;
    public Integer endurancemin;
    public Integer endurancemax;
    public Integer intelligencemin;
    public Integer intelligencemax;
    public Integer charismamin;
    public Integer charismamax;
    public Integer perceptionmin;
    public Integer perceptionmax;
    public Integer luckmin;
    public Integer luckmax;
    public Integer heightmin;
    public Integer heightmax;
    public Integer weightmin;
    public Integer weightmax;
    public Instant creationDate;
    public String creationAuthor;
    public Instant lastModificationDate;
    public String lastModificationAuthor;
    public Integer version;;
    public List<GenderDTO> theGenders;;
    public List<ModelDTO> theModels;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}