version: '3.1'

services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: game
      POSTGRES_PASSWORD: game
      POSTGRES_DB: game
    volumes:
      - ./postgres-data:/var/lib/postgresql
    networks:
      - back-tier
  admin:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    networks:
      - back-tier
networks:
  back-tier: