//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/app.routes.ts.p.vm
//
import { ModuleWithProviders }  from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { HomeComponent } from './home.component';

import { CategoryTypeListComponent } from './entities/categoryType/categoryType-list.component';
import { CategoryTypeDetailComponent } from './entities/categoryType/categoryType-detail.component';

import { CharacterListComponent } from './entities/character/character-list.component';
import { CharacterDetailComponent } from './entities/character/character-detail.component';

import { CharacteristicListComponent } from './entities/characteristic/characteristic-list.component';
import { CharacteristicDetailComponent } from './entities/characteristic/characteristic-detail.component';

import { GenderListComponent } from './entities/gender/gender-list.component';
import { GenderDetailComponent } from './entities/gender/gender-detail.component';

import { ModelListComponent } from './entities/model/model-list.component';
import { ModelDetailComponent } from './entities/model/model-detail.component';

import { RaceListComponent } from './entities/race/race-list.component';
import { RaceDetailComponent } from './entities/race/race-detail.component';

import { RaceOptionListComponent } from './entities/raceOption/raceOption-list.component';
import { RaceOptionDetailComponent } from './entities/raceOption/raceOption-detail.component';

import { ScriptListComponent } from './entities/script/script-list.component';
import { ScriptDetailComponent } from './entities/script/script-detail.component';

import { SkillListComponent } from './entities/skill/skill-list.component';
import { SkillDetailComponent } from './entities/skill/skill-detail.component';

import { UserListComponent } from './entities/user/user-list.component';
import { UserDetailComponent } from './entities/user/user-detail.component';

export const routes: Routes = [
    { path : '',  component: HomeComponent }
    ,
    {path: 'categoryType-list', component: CategoryTypeListComponent },
    {path: 'categoryType/:id', component: CategoryTypeDetailComponent }
    ,
    {path: 'character-list', component: CharacterListComponent },
    {path: 'character/:id', component: CharacterDetailComponent }
    ,
    {path: 'characteristic-list', component: CharacteristicListComponent },
    {path: 'characteristic/:id', component: CharacteristicDetailComponent }
    ,
    {path: 'gender-list', component: GenderListComponent },
    {path: 'gender/:id', component: GenderDetailComponent }
    ,
    {path: 'model-list', component: ModelListComponent },
    {path: 'model/:id', component: ModelDetailComponent }
    ,
    {path: 'race-list', component: RaceListComponent },
    {path: 'race/:id', component: RaceDetailComponent }
    ,
    {path: 'raceOption-list', component: RaceOptionListComponent },
    {path: 'raceOption/:id', component: RaceOptionDetailComponent }
    ,
    {path: 'script-list', component: ScriptListComponent },
    {path: 'script/:id', component: ScriptDetailComponent }
    ,
    {path: 'skill-list', component: SkillListComponent },
    {path: 'skill/:id', component: SkillDetailComponent }
    ,
    {path: 'user-list', component: UserListComponent },
    {path: 'user/:id', component: UserDetailComponent }
];

export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
