//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/app.module.ts.p.vm
//
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations'
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule  }  from '@angular/router';
import { MaterialModule, MdDatepickerModule, MdNativeDateModule } from '@angular/material';
import { ConfirmDialogModule, FileUploadModule, PanelModule, GrowlModule, MenubarModule, DialogModule, ButtonModule, AutoCompleteModule, DataTableModule, SharedModule, DropdownModule,PickListModule,CheckboxModule,TriStateCheckboxModule, InputTextModule,InputTextareaModule,CalendarModule,PasswordModule,TabViewModule } from 'primeng/primeng';
import { ConfirmationService } from 'primeng/primeng';
import { AppComponent }   from './app.component';
import { HomeComponent }  from './home.component';
import { AuthService } from './service/auth.service';
import { MessageService } from './service/message.service';
import { routing }        from './app.routes';
import { EmailValidator } from './support/email.validator';
import { ConfirmDeleteDialogComponent } from './support/confirm-delete-dialog.component';


// CategoryType ...
import { CategoryTypeService } from './entities/categoryType/categoryType.service';
import { CategoryTypeListComponent } from './entities/categoryType/categoryType-list.component';
import { CategoryTypeDetailComponent } from './entities/categoryType/categoryType-detail.component';
import { CategoryTypeLineComponent } from './entities/categoryType/categoryType-line.component';
import { CategoryTypeCompleteComponent } from './entities/categoryType/categoryType-auto-complete.component';

// Character ...
import { CharacterService } from './entities/character/character.service';
import { CharacterListComponent } from './entities/character/character-list.component';
import { CharacterDetailComponent } from './entities/character/character-detail.component';
import { CharacterLineComponent } from './entities/character/character-line.component';
import { CharacterCompleteComponent } from './entities/character/character-auto-complete.component';

// Characteristic ...
import { CharacteristicService } from './entities/characteristic/characteristic.service';
import { CharacteristicListComponent } from './entities/characteristic/characteristic-list.component';
import { CharacteristicDetailComponent } from './entities/characteristic/characteristic-detail.component';
import { CharacteristicLineComponent } from './entities/characteristic/characteristic-line.component';
import { CharacteristicCompleteComponent } from './entities/characteristic/characteristic-auto-complete.component';

// Gender ...
import { GenderService } from './entities/gender/gender.service';
import { GenderListComponent } from './entities/gender/gender-list.component';
import { GenderDetailComponent } from './entities/gender/gender-detail.component';
import { GenderLineComponent } from './entities/gender/gender-line.component';
import { GenderCompleteComponent } from './entities/gender/gender-auto-complete.component';

// Model ...
import { ModelService } from './entities/model/model.service';
import { ModelListComponent } from './entities/model/model-list.component';
import { ModelDetailComponent } from './entities/model/model-detail.component';
import { ModelLineComponent } from './entities/model/model-line.component';
import { ModelCompleteComponent } from './entities/model/model-auto-complete.component';

// Race ...
import { RaceService } from './entities/race/race.service';
import { RaceListComponent } from './entities/race/race-list.component';
import { RaceDetailComponent } from './entities/race/race-detail.component';
import { RaceLineComponent } from './entities/race/race-line.component';
import { RaceCompleteComponent } from './entities/race/race-auto-complete.component';

// RaceOption ...
import { RaceOptionService } from './entities/raceOption/raceOption.service';
import { RaceOptionListComponent } from './entities/raceOption/raceOption-list.component';
import { RaceOptionDetailComponent } from './entities/raceOption/raceOption-detail.component';
import { RaceOptionLineComponent } from './entities/raceOption/raceOption-line.component';
import { RaceOptionCompleteComponent } from './entities/raceOption/raceOption-auto-complete.component';

// Script ...
import { ScriptService } from './entities/script/script.service';
import { ScriptListComponent } from './entities/script/script-list.component';
import { ScriptDetailComponent } from './entities/script/script-detail.component';
import { ScriptLineComponent } from './entities/script/script-line.component';
import { ScriptCompleteComponent } from './entities/script/script-auto-complete.component';

// Skill ...
import { SkillService } from './entities/skill/skill.service';
import { SkillListComponent } from './entities/skill/skill-list.component';
import { SkillDetailComponent } from './entities/skill/skill-detail.component';
import { SkillLineComponent } from './entities/skill/skill-line.component';
import { SkillCompleteComponent } from './entities/skill/skill-auto-complete.component';

// User ...
import { UserService } from './entities/user/user.service';
import { UserListComponent } from './entities/user/user-list.component';
import { UserDetailComponent } from './entities/user/user-detail.component';
import { UserLineComponent } from './entities/user/user-line.component';
import { UserCompleteComponent } from './entities/user/user-auto-complete.component';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    EmailValidator,
    ConfirmDeleteDialogComponent
    ,
    CategoryTypeListComponent,
    CategoryTypeDetailComponent,
    CategoryTypeLineComponent,
    CategoryTypeCompleteComponent
    ,
    CharacterListComponent,
    CharacterDetailComponent,
    CharacterLineComponent,
    CharacterCompleteComponent
    ,
    CharacteristicListComponent,
    CharacteristicDetailComponent,
    CharacteristicLineComponent,
    CharacteristicCompleteComponent
    ,
    GenderListComponent,
    GenderDetailComponent,
    GenderLineComponent,
    GenderCompleteComponent
    ,
    ModelListComponent,
    ModelDetailComponent,
    ModelLineComponent,
    ModelCompleteComponent
    ,
    RaceListComponent,
    RaceDetailComponent,
    RaceLineComponent,
    RaceCompleteComponent
    ,
    RaceOptionListComponent,
    RaceOptionDetailComponent,
    RaceOptionLineComponent,
    RaceOptionCompleteComponent
    ,
    ScriptListComponent,
    ScriptDetailComponent,
    ScriptLineComponent,
    ScriptCompleteComponent
    ,
    SkillListComponent,
    SkillDetailComponent,
    SkillLineComponent,
    SkillCompleteComponent
    ,
    UserListComponent,
    UserDetailComponent,
    UserLineComponent,
    UserCompleteComponent
    ],
    imports: [
// angular
        BrowserModule,
        BrowserAnimationsModule,
        FormsModule,
        HttpModule,

// angular material,
        MaterialModule,
        MdDatepickerModule,
        MdNativeDateModule,

// primeng
        ConfirmDialogModule,
        FileUploadModule,
        PanelModule,
        GrowlModule,
        MenubarModule,
        DialogModule,
        ButtonModule,
        AutoCompleteModule,
        DataTableModule,
        SharedModule,
        DropdownModule,
        PickListModule,
        CheckboxModule,
        TriStateCheckboxModule,
        InputTextModule,
        InputTextareaModule,
        CalendarModule,
        PasswordModule,
        TabViewModule,

// our application routes
        routing
    ],
    providers: [
// our application entity services
        CategoryTypeService,
        CharacterService,
        CharacteristicService,
        GenderService,
        ModelService,
        RaceService,
        RaceOptionService,
        ScriptService,
        SkillService,
        UserService,

// our application services
        AuthService,
        MessageService,

// primeng service
        ConfirmationService
    ],
    entryComponents: [ConfirmDeleteDialogComponent],
    bootstrap: [ AppComponent ]
})
export class AppModule {}
