//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {Characteristic} from './characteristic';
import {CharacteristicService} from './characteristic.service';
import {Character} from '../character/character';

@Component({
    moduleId: module.id,
	templateUrl: 'characteristic-detail.component.html',
	selector: 'characteristic-detail',
})
export class CharacteristicDetailComponent implements OnInit, OnDestroy {
    characteristic : Characteristic;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<Characteristic>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private characteristicService: CharacteristicService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for characteristic-detail ' + id);

            if (id === 'new') {
                this.characteristic = new Characteristic();
            } else {
                this.characteristicService.getCharacteristic(id)
                    .subscribe(characteristic => {
                            this.characteristic = characteristic;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.characteristicService.update(this.characteristic).
            subscribe(
                characteristic => {
                    this.characteristic = characteristic;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.characteristic);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
