//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, OnChanges, EventEmitter, SimpleChanges } from '@angular/core';
import { Router } from '@angular/router';
import { DataTable, LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { MdDialog } from '@angular/material';
import { ConfirmDeleteDialogComponent } from "../../support/confirm-delete-dialog.component";
import { Skill } from './skill';
import { SkillDetailComponent } from './skill-detail.component';
import { SkillService } from './skill.service';
import { SkillLineComponent } from '../skill/skill-line.component';
import { Script } from '../script/script';
import { ScriptLineComponent } from '../script/script-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'skill-list.component.html',
	selector: 'skill-list'
})
export class SkillListComponent {

    @Input() header = "Skills...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    skillToDelete : Skill;

    // basic search criterias (visible if not in 'sub' mode)
    example : Skill = new Skill();

    // list is paginated
    currentPage : PageResponse<Skill> = new PageResponse<Skill>(0,0,[]);

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _skill2 : Skill;
    private _script : Script;

    constructor(private router : Router,
        private skillService : SkillService,
        private messageService : MessageService,
        private confirmDeleteDialog: MdDialog) {
    }

    /**
     * When used as a 'sub' component (to display one-to-many list), refreshes the table
     * content when the input changes.
     */
    ngOnChanges(changes: SimpleChanges) {
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.skillService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set skill2(skill2 : Skill) {
        if (skill2 == null) {
            return;
        }
        this._skill2 = skill2;

        this.example = new Skill();
        this.example.skill2 = new Skill();
        this.example.skill2.id = this._skill2.id;
    }

    @Input()
    set script(script : Script) {
        if (script == null) {
            return;
        }
        this._script = script;

        this.example = new Skill();
        this.example.script = new Script();
        this.example.script.id = this._script.id;
    }


    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/skill', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/skill', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let skillToDelete : Skill = <Skill> rowData;

        let dialogRef = this.confirmDeleteDialog.open(ConfirmDeleteDialogComponent);
        dialogRef.afterClosed().subscribe(result => {
            if (result === 'delete') {
                this.delete(skillToDelete);
            }
        });
    }

    private delete(skillToDelete : Skill) {
        let id =  skillToDelete.id;

        this.skillService.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(skillToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}