//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {Skill} from './skill';
import {SkillService} from './skill.service';
import {Script} from '../script/script';
import {Character} from '../character/character';
import {CharacterService} from '../character/character.service';

@Component({
    moduleId: module.id,
	templateUrl: 'skill-detail.component.html',
	selector: 'skill-detail',
})
export class SkillDetailComponent implements OnInit, OnDestroy {
    skill : Skill;

    private params_subscription: any;

    sourceTheChars : Character[] = [];

    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new Skill
    set skill2(skill2 : Skill) {
        this.skill = new Skill();
        this.skill.skill2 = skill2;
    }

    @Input() // used to pass the parent when creating a new Skill
    set script(script : Script) {
        this.skill = new Skill();
        this.skill.script = script;
    }

    @Output() onSaveClicked = new EventEmitter<Skill>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private skillService: SkillService, private characterService : CharacterService) {
        characterService.complete(null).
            subscribe(theChars => this.sourceTheChars = theChars,
                        error =>  this.messageService.error('Constructor error', error));
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for skill-detail ' + id);

            if (id === 'new') {
                this.skill = new Skill();
            } else {
                this.skillService.getSkill(id)
                    .subscribe(skill => {
                            this.skill = skill;
                            this.sourceTheChars = this.sourceTheChars.filter(item => this.skill.theChars.map((e) => e.id).indexOf(item.id) < 0);
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoSkill2() {
        this.router.navigate(['/skill', this.skill.skill2.id]);
    }

    clearSkill2() {
        this.skill.skill2 = null;
    }

    gotoScript() {
        this.router.navigate(['/script', this.skill.script.id]);
    }

    clearScript() {
        this.skill.script = null;
    }

    onSave() {
        this.skillService.update(this.skill).
            subscribe(
                skill => {
                    this.skill = skill;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.skill);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
